services:
  - type: web
    name: musclelite
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn musclelites.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: DJANGO_SETTINGS_MODULE
        value: musclelites.settings